<?
//This file generated by Liquidweb migrations team, feel free to remove if no longer needed.
echo "<h2>Server info</h2>";

echo "You're accessing: " . $_SERVER['HTTP_HOST'] . "<br>"; //or $_SERVER['SERVER_NAME']

echo "This server's Ip: " . $_SERVER['SERVER_ADDR'] . "<br>";

echo "This server's hostname: ";
if (function_exists('gethostname')) {
  echo gethostname() ;
} else {
  //for php < 5.3
  echo php_uname('n');
}
echo "<br>";
?>

